#==============================
rule all:
#==============================
    input:
        log_snake=config['out_path']+"/log.Snakefile",
        outnpy=expand(config['out_path']+"/{ID}/base_mismatch_perc.npy", ID=config["ID"])

#Create log file for Snakefile
#==============================
rule log_snake:
#==============================
  output: config['out_path']+"/log.Snakefile"
  shell:  """
          cp ./Snakefile {output}
          """

#Run RNA mut rule
#==============================
rule RNA_mut:
#==============================
    input:
        inp=config['in_path']+"/{ID}/Aligned.sortedByCoord.out.bam"
    output:
        outnpy=config['out_path']+"/{ID}/base_mismatch_perc.npy",
        
    conda:
        "RNA_mut.yaml"

    script:
        "RNA_mut.py"

